#ifndef H_MAIN_CLIENT_CONFIG_FILE
#define H_MAIN_CLIENT_CONFIG_FILE

//MC means MainClient

//window
#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 800
#define WINDOW_TITLE "Fluffy Multiplayer App"
#define WINDOW_BACKGROUND_COLOR sf::Color(40,42,48)
#define FORM_HIDE_CHARECTER '*'
#define STATES_ASSET_PATH "./assets/states/"

#define MS_DATA_ENCRYPT_DECRYPT_SHIFT 5

#define MC_PATH_TO_FONTS "./assets/fonts/"
#define MC_DEFAULT_FONT "arial.ttf"

#define GAME_CLIENT_APPLICATION_PATH "../game-client/"
#define GAME_CLIENT_APPLICATION_NAME "gc.run"

#define MC_SHOW_ERROR_NOTIFICATIONS true
#define MC_SHOW_SUCCESS_NOTIFICATIONS false
#define MC_DEFAULT_PORT 13333

#define MC_RECEIVE_BUFFER 1024
#define CLIENT_LOCAL_SERVER_LIST_FILE "serverlist.txt"
#define CLIENT_LOCAL_APP_CONFIG_FILE "identity.ini"

#define MC_IP_PORT_SEPARATOR ":"
#define MC_IP_PORT_ENDLINE ";"

#define MC_APP_CONFIG_IDENTITY_KEY "identity"
#define MC_APP_CONFIG_SEPERATOR "="
#define MC_APP_CONFIG_ENDLINE ";"
#define MC_IDENTITY_MIN_LENGTH 59
#define MC_IDENTITY_MAX_LENGTH 60

#define MC_DATA_START_AT_INDEX 3

#define MC_REQUEST_DELIMITER ",&"
#define MC_REQUEST_CLOSER "~"
#define MC_RESPONSE_DELIMITER MC_REQUEST_DELIMITER
#define MC_RESPONSE_CLOSER MC_REQUEST_CLOSER


#define MC_SERVER_DEFAULT_IP "127.0.0.1"
#define MC_SERVER_DEFAULT_PORT 8888
#define MC_SERVER_IP_NOT_ALLOWED_LIST {"0.0.0.0"}

#define MC_REQUEST_TIMEOUT 100
#define MC_STATE_BIND_PICK_PORT_TRY_COUNT 10

#define MC_MINUMUM_RESPONSE_CODE 100
//internal and external erros included
#define MC_ERROR_RESPONSE_CODE_MIN 400
#define MC_ERROR_RESPONSE_CODE_MAX 599
#define MC_SUCCESS_RESPONSE_CODE_MIN 200
#define MC_SUCCESS_RESPONSE_CODE_MAX 399
#define MC_RESPONSE_POSITION_MIN_INDEX 0
#define MC_RESPONSE_POSITION_MAX_INDEX 3

#define GAME_MODE_LIST {"Unknown","Mensch","Chess","TicTacToe"}
#define GAME_MODE_TEXTURE_LIST {"unknown.png","gm-mensch.png","gm-chess.png","gm-tictatoe.png"}
#define MAX_PLAYER_LIST {"2","4","6","8","10","12","14","16","18","20","30"}

#define MS_GET_LOBBY_LIST_COUNT_OF_RESULTS 10
#define MS_GET_LOBBY_LIST_LOBBY_FILEDS 12
#define MS_MAINPAGE_LOBBY_CELL_X_PADDING 100.0
#define MS_MAINPAGE_LOBBY_CELL_Y_PADDING 50.0

#define UI_COMPONENT_TEXTURE_DEFAULT "./somewhere/componentTextureNotFound.png"
#define UI_COMPONENT_FONT_DEFAULT "./somewhere/componentFontNotFound.ttf"


//---------------------------- Form Elements
#define FE_PATH_TO_ASSETS "./assets/uiComponents/"

//TI means Text Input
#define TI_DEFAULT_FONT_PATH MC_PATH_TO_FONTS MC_DEFAULT_FONT
#define TI_DEFAULT_FONT_SIZE 17
#define TI_DEFAULT_FORGROUND_COLOR sf::Color::White
#define TI_DEFAULT_BACKGROUND_COLOR sf::Color::White
#define TI_DEFAULT_SIZE 100,70
#define TI_DEFAULT_STYLE sf::Text::Bold
#define TI_DEFAULT_POSITION_X 400
#define TI_DEFAULT_POSITION_Y 250

#define TI_TITLE_PADDING_X 0.0
#define TI_TITLE_PADDING_Y 25.0
#define TI_ERROR_PADDING_X 200.0
#define TI_ERROR_PADDING_Y 25.0
#define TI_INPUTBOX_PADDING_X 0.0 //also mainText will this this
#define TI_INPUTBOX_PADDING_Y 0.0 //also mainText will this this
#define TI_TEXTURE_INPUT_BOX "textInputTexture.png"


//TIP means Text Input Password
#define TIP_BUTTON_VISIBLE_PASSWORD_PADDING_X (0.0,0.0)
#define TIP_BUTTON_VISIBLE_PASSWORD_PADDING_Y (0.0,0.0)
#define TIP_TEXTURE_BUTTON_VISIBLE_PASSWORD_ON "passwordVisibleButtonTexture.png"
#define TIP_TEXTURE_BUTTON_VISIBLE_PASSWORD_OFF "passwordInvisbleButtonTexture.png"


//button component
#define BUTTON_TEXTURE "buttonTexture.png"
#define BUTTON_DEFAULT_BACKGROUND_COLOR sf::Color::White
#define BUTTON_DEFAULT_FORGROUND_COLOR sf::Color::Black
#define BUTTON_DEFAULT_SIZE_WIDTH 20
#define BUTTON_DEFAULT_SIZE_HEIGHT 10
#define BUTTON_DEFAULT_STYLE sf::Text::Bold
#define BUTTON_DEFAULT_FONT_SIZE 17
#define BUTTON_DEFAULT_POS_X 10.0
#define BUTTON_DEFAULT_POS_Y 10.0


//picture button component
#define PICTURE_BUTTON_REFRESH_LOBBY_LIST_TEXTURE "pictureButtonRefreshLobbyListTexture.png"
#define PICTURE_BUTTON_LOGOUT_TEXTURE "pictureButtonLogoutTexture.png"
#define PICTURE_BUTTON_QUIT_TEXTURE "pictureButtonQuitTexture.png"
#define PICTURE_BUTTON_TEXT_POS_X 0.0
#define PICTURE_BUTTON_TEXT_POS_Y 35.0

//checkBox component
#define CHECKBOX_DEFAULT_TEXT "checkbox"
#define CHECKBOX_CHECKED_TEXTURE "checkBoxCheckedTexture.png"
#define CHECKBOX_UNCHECKED_TEXTURE "checkBoxUncheckedTexture.png"
#define CHECKBOX_DEFAULT_FORGROUND_COLOR sf::Color::White
#define CHECKBOX_DEFAULT_BACKGROUND_COLOR sf::Color::Black
#define CHECKBOX_DEFAULT_POS_X 10.0
#define CHECKBOX_DEFAULT_POS_Y 10.0
#define CHECKBOX_DEFAULT_SIZE_WIDTH 20
#define CHECKBOX_DEFAULT_SIZE_HEIGHT 10
#define CHECKBOX_DEFAULT_FONT_SIZE 17
#define CHECKBOX_DEFAULT_STATUS false
#define CHECKBOX_DEFAULT_STYLE sf::Text::Bold
#define CHECKBOX_BOX_PADDING_X 115


//spinBox component
#define SPINBOX_DEFAULT_TEXT "spinbox"
#define SPINBOX_DEAULT_ITEMS {"exampleA","exampleB","exampleC"}
#define SPINBOX_TEXTURE "spinBoxTexture.png"
#define SPINBOX_DEFAULT_FORGROUND_COLOR sf::Color::White
#define SPINBOX_DEFAULT_BACKGROUND_COLOR sf::Color::Black
#define SPINBOX_DEFAULT_POS_X 10.0
#define SPINBOX_DEFAULT_POS_Y 10.0
#define SPINBOX_DEFAULT_SIZE_WIDTH 20
#define SPINBOX_DEFAULT_SIZE_HEIGHT 10
#define SPINBOX_DEFAULT_FONT_SIZE 17
#define SPINBOX_DEFAULT_ITEM 0
#define SPINBOX_DEFAULT_STYLE sf::Text::Bold
#define SPINBOX_SPIN_BUTTON_PADDING_X 225
#define SPINBOX_SPIN_BUTTON_PADDING_Y 35


//icon text component
#define ICON_TEXT_TEXT_PADDING_X +0.0
#define ICON_TEXT_TEXT_PADDING_Y +30.0
#define ICON_TEXT_DEFAULT_FONT_SIZE 17
#define ICON_TEXT_DEFAULT_STYLE sf::Text::Bold


//lobby cel component
#define LOBBY_CELL_ROTATE_VALUE 25.f
#define LOBBY_CELL_PLAYERS_STATUS_FONT_SIZE 13
#define LOBBY_CELL_INGAME_STATUS_FONT_SIZE 13
#define LOBBY_CELL_INGAME_STATUS_TRUE "in-game"
#define LOBBY_CELL_INGAME_STATUS_FALSE "in-lobby"
#define LOBBY_CELL_RECTANGLE_TEXTURE "lobbyRect.png"
#define LOBBY_CELL_INFO_PRIVATE_LOBBY_TEXTURE "lobbyPrivate.png"
#define LOBBY_CELL_INFO_LOCKED_LOBBY_TEXTURE "lobbyLocked.png"
#define LOBBY_CELL_INFO_PLAYERS_STATUS_TEXTURE "lobbyPlayers.png"
#define LOBBY_CELL_INFO_TEXTCHAT_DISABLED_TEXTURE "lobbyTextChatDisabled.png"
#define LOBBY_CELL_INFO_TEXTCHAT_ENABLED_TEXTURE "lobbyTextChatEnabled.png"
#define LOBBY_CELL_INFO_VOICECHAT_DISABLED_TEXTURE "lobbyVoiceChatDisabled.png"
#define LOBBY_CELL_INFO_VOICECHAT_ENABLED_TEXTURE "lobbyVoiceChatEnabled.png"
#define LOBBY_CELL_INFO_SPECTER_DISABLED_TEXTURE "lobbySpecterDisabled.png"
#define LOBBY_CELL_INFO_SPECTER_ENABLED_TEXTURE "lobbySpecterEnabled.png"
#define LOBBY_CELL_VOICE_STATUS_PADDING_X +20.0
#define LOBBY_CELL_VOICE_STATUS_PADDING_Y +65.0
#define LOBBY_CELL_TEXT_STATUS_PADDING_X +135.0
#define LOBBY_CELL_TEXT_STATUS_PADDING_Y +65.0
#define LOBBY_CELL_SPECTER_STATUS_PADDING_X +80.0
#define LOBBY_CELL_SPECTER_STATUS_PADDING_Y +17.0
#define LOBBY_CELL_LOCKED_STATUS_PADDING_X +0.0
#define LOBBY_CELL_LOCKED_STATUS_PADDING_Y +0.0
#define LOBBY_CELL_PLAYERS_STATUS_PADDING_X +75.0
#define LOBBY_CELL_PLAYERS_STATUS_PADDING_Y +120.0
#define LOBBY_CELL_INGAME_STATUS_PADDING_X +75.0
#define LOBBY_CELL_INGAME_STATUS_PADDING_Y +100.0
#define LOBBY_CELL_PRIVATE_STATUS_PADDING_X +45.0
#define LOBBY_CELL_PRIVATE_STATUS_PADDING_Y +45.0
#define LOBBY_CELL_GAMEMODE_STATUS_PADDING_X +80.0
#define LOBBY_CELL_GAMEMODE_STATUS_PADDING_Y +65.0

#define NOTIFICATIONBOX_BACKGROUND_TEXTURE "notificationBackgroundTexture.png"
#define NOTIFICATIONBOX_CLOSE_BUTTON_TEXTURE "notificationCloseButtonTexture.png"
#define NOTIFICATIONBOX_COPY_ERROR_BUTTON_TEXTURE "notificationCopyButtonTexture.png"

#define NOTIFICATIONBOX_BACK_OF_BACKGROUND_COLOR sf::Color::Transparent
#define NOTIFICATIONBOX_BACK_OF_BACKGROUND_WIDTH_PERCENT 100
#define NOTIFICATIONBOX_BACK_OF_BACKGROUND_HEIGHT_PERCENT 100

//make them into center of screen
#define INITAL_TEXT_ON_SCREEN_PADDING_X -70
#define INITAL_TEXT_ON_SCREEN_PADDING_Y -70


#define NOTIFICATIONBOX_TITLE_FONT_SIZE 18
#define NOTIFICATIONBOX_MESSAGE_FONT_SIZE 17

#define NOTIFICATIONBOX_BACKGROUND_PADDING_X +0.0
#define NOTIFICATIONBOX_BACKGROUND_PADDING_Y +0.0

#define NOTIFICATIONBOX_TITLE_PADDING_X +5.0
#define NOTIFICATIONBOX_TITLE_PADDING_Y +5.0

#define NOTIFICATIONBOX_MESSAGE_PADDING_X +5.0
#define NOTIFICATIONBOX_MESSAGE_PADDING_Y +25.0

#define NOTIFICATIONBOX_CLOSEBUTTON_PADDING_X +480.0
#define NOTIFICATIONBOX_CLOSEBUTTON_PADDING_Y +5.0

#define NOTIFICATIONBOX_COPYBUTTON_PADDING_X +440.0
#define NOTIFICATIONBOX_COPYBUTTON_PADDING_Y +5.0

#endif
