#ifndef LOBBY_REQUEST_RESPONSE_LIST
#define LOBBY_REQUEST_RESPONSE_LIST


// ------------------------- request, range: 100 -> 200
#define CONNECT_TO_LOBBY 100
#define RECONNECT_TO_LOBBY 101
#define DISCONNECT_FROM_LOBBY 102
#define ENTERED_LOBBY_PASSWORD 103
#define SEND_TEXT_CHAT 104
#define SEND_VOICE_CHAT 105
#define GET_LOBBY_SETTINGS 106
#define UPDATE_LOBBY_SETTINGS 107
#define GET_LOBBY_INFO 108
#define START_GAME 109
#define STOP_GAME 110
#define DELETE_LOBBY 111
#define KICK_PLAYER 112
#define BAN_PLAYER 113
#define TRANSFER_LOBBY_OWNERSHIP 114


// ------------------------- responses, range: 201 -> 500
#define CONNECTION_ACCEPTED
#define CONNECTION_NOT_FOUND
#define CONNECTION_EXISTS
#define LOBBY_IS_FULL
#define CONNECTION_REJECTED
#define RECONNECT_ACCEPTED
#define RECONNECT_REJECTED
#define DISCONNECTED
#define PASSWORD_INCORRECT
#define PASSWORD_ACCEPTED
#define TEXT_CHAT_IS_DISABLED
#define VOICE_CHAT_IS_DISABLED
#define A_NEW_TEXT_MESSAGE
#define A_NEW_VOICE_MESSAGE
#define GET_LOBBY_SETTINGS_SUCCESS
#define GET_LOBBY_SETTINGS_FAILED_NO_PERMISSION
#define UPDATE_LOBBY_SETTINGS_ACCEPTED
#define UPDATE_LOBBY_SETTINGS_REJECTED_NO_PERMISSON
#define UPDATE_LOBBY_SETTINGS_FAILED
#define START_GAME_ACCEPTED
#define START_GAME_REJECTED_NO_PERMISSION
#define START_GAME_FAILED
#define START_GAME_FAILED_GAME_HAS_BEEN_STARTED_ALREADY
#define STOP_GAME_ACCEPTED
#define STOP_GAME_FAILED
#define STOP_GAME_REJECTED_NO_PERMISSION
#define STOP_GAME_FAILED_GAME_IS_NOT_STARTED
#define DELETE_LOBBY_ACCEPTED
#define DELETE_LOBBY_FAILED
#define DELETE_LOBBY_REJECTED_NO_PERMISSION
#define KICK_PLAYER_ACCEPTED
#define KICK_PLAYER_FAIELD
#define KICK_PLAYER_REJECTED_NO_PERMISSION
#define BAN_PLAYER_ACCEPTED
#define BAN_PLAYER_REJECTED
#define BAN_PLAYER_FAILED_NO_PERMISSION
#define BAN_PLAYER_FAILED_TARGET_NOT_FOUND
#define TRANSFER_LOBBY_OWNERSHIP_ACCEPTED
#define TRANSFER_LOBBY_OWNERSHIP_REJECTED
#define TRANSFER_LOBBY_OWNERSHIP_REJECTED_NO_PERMISSION
#define TRANSFER_LOBBY_OWNERSHIP_REJECTED_TARGET_NOT_FOUND


#endif
