#ifndef LOBBY_REQUEST_RESPONSE_LIST
#define LOBBY_REQUEST_RESPONSE_LIST


// ------------------------- request, range: 100 -> 200

//lobby
#define REQUEST_CONNECT_TO_LOBBY 100
#define REQUEST_RECONNECT_TO_LOBBY 101
#define REQUEST_DISCONNECT_FROM_LOBBY 102
#define REQUEST_ENTERED_LOBBY_PASSWORD 103
#define REQUEST_GET_LOBBY_SETTINGS 104
#define REQUEST_UPDATE_LOBBY_SETTINGS 105
#define REQUEST_GET_LOBBY_INFO 106
#define REQUEST_START_GAME 107
#define REQUEST_STOP_GAME 108
#define REQUEST_DELETE_LOBBY 109
#define REQUEST_KICK_PLAYER 110
#define REQUEST_BAN_PLAYER 111
#define REQUEST_TRANSFER_LOBBY_OWNERSHIP 112

//text chat
#define REQUEST_SEND_TEXT_CHAT 120

//voice chat
#define REQUEST_SEND_VOICE_CHAT 130
#define REQUEST_ENABLE_VOICE_CHAT 131 //add client to voice chats
#define REQUEST_DISABLE_VOICE_CHAT 132 //exit client from voice chats



// ------------------------- responses, range: 201 -> 500
//if there is no comment after resposne code that will be send only to sender


// = = = success 201
#define RESPONSE_CONNECTION_ACCEPTED


// = = = errors 301


// = = = internal errors 401

#define RESPONSE_CONNECTION_NOT_FOUND
#define RESPONSE_CONNECTION_EXISTS

#define RESPONSE_LOBBY_IS_FULL
#define RESPONSE_CONNECTION_REJECTED
#define RESPONSE_RECONNECT_ACCEPTED
#define RESPONSE_RECONNECT_REJECTED
#define RESPONSE_DISCONNECTED
#define RESPONSE_PASSWORD_INCORRECT
#define RESPONSE_PASSWORD_ACCEPTED
#define RESPONSE_TEXT_CHAT_IS_DISABLED
#define RESPONSE_VOICE_CHAT_IS_DISABLED
#define RESPONSE_A_NEW_TEXT_MESSAGE
#define RESPONSE_A_NEW_VOICE_MESSAGE
#define RESPONSE_GET_LOBBY_SETTINGS_SUCCESS
#define RESPONSE_GET_LOBBY_SETTINGS_FAILED_NO_PERMISSION
#define RESPONSE_UPDATE_LOBBY_SETTINGS_ACCEPTED
#define RESPONSE_UPDATE_LOBBY_SETTINGS_REJECTED_NO_PERMISSON
#define RESPONSE_UPDATE_LOBBY_SETTINGS_FAILED
#define RESPONSE_START_GAME_ACCEPTED
#define RESPONSE_START_GAME_REJECTED_NO_PERMISSION
#define RESPONSE_START_GAME_FAILED
#define RESPONSE_START_GAME_FAILED_GAME_HAS_BEEN_STARTED_ALREADY
#define RESPONSE_STOP_GAME_ACCEPTED
#define RESPONSE_STOP_GAME_FAILED
#define RESPONSE_STOP_GAME_REJECTED_NO_PERMISSION
#define RESPONSE_STOP_GAME_FAILED_GAME_IS_NOT_STARTED
#define RESPONSE_DELETE_LOBBY_ACCEPTED
#define RESPONSE_DELETE_LOBBY_FAILED
#define RESPONSE_DELETE_LOBBY_REJECTED_NO_PERMISSION
#define RESPONSE_KICK_PLAYER_ACCEPTED
#define RESPONSE_KICK_PLAYER_FAIELD
#define RESPONSE_KICK_PLAYER_REJECTED_NO_PERMISSION
#define RESPONSE_BAN_PLAYER_ACCEPTED
#define RESPONSE_BAN_PLAYER_REJECTED
#define RESPONSE_BAN_PLAYER_FAILED_NO_PERMISSION
#define RESPONSE_BAN_PLAYER_FAILED_TARGET_NOT_FOUND
#define RESPONSE_TRANSFER_LOBBY_OWNERSHIP_ACCEPTED
#define RESPONSE_TRANSFER_LOBBY_OWNERSHIP_REJECTED
#define RESPONSE_TRANSFER_LOBBY_OWNERSHIP_REJECTED_NO_PERMISSION
#define RESPONSE_TRANSFER_LOBBY_OWNERSHIP_REJECTED_TARGET_NOT_FOUND


#endif
