#ifndef H_MAIN_SERVER_REQUEST_LIST
#define H_MAIN_SERVER_REQUEST_LIST

#define MS_REQUEST_CONNECT 100
#define MS_REQUEST_DISCONNECT 101
#define MS_REQUEST_LOGIN 102
#define MS_REQUEST_REGISTER 103
#define MS_REQUEST_CREATE_LOBBY 104
#define MS_REQUEST_GET_LOBBY_LIST 105
#define MS_REQUEST_GET_LOBBY_INFO 106
#define MS_REQUEST_LATEST_VERSION 107

#endif
